### ISSUE TITLE
Publish comments from GS to Figma • Публиковать комментарии из GS в Figma

### ISSUE THREAD

**Issue by olgapavlova** [eduhund/figmasheet#15]
As Figma comments.

----------------------------------------------------------

Сразу в форме комментариев.

**Comment by olgapavlova** [comment]
Для реализации нужен Figma API — то есть это непросто сделать.
Плюс UX не совсем понятен: а как обратно засасывать? А нужна ли вся дискуссия?
Пока кажется, что комментарии — очень отдельная функциональность. Точно не для MVP.

**Comment by olgapavlova** [comment]
Если отказаться от требования «Комментарии должны быть комментариями», то всё сразу становится проще. Можно будет создать специальный фрейм со списком этих комментариев. Но удобство падает, конечно.

**Comment by olgapavlova** [comment]
Для публичного бета-релиза — делаем, но до идеала не вылизываем.

**Comment by roman-nebel** [comment]
Базовая фича сделана. Остались доработки:
- Повторную загрузку текстов с коммент ариями (сейчас список комментов и бейджи задулбируются)
- Перелинковку бейджей и комментарией
- Выгрузку статусов комментариев вместе с текстами (для хоть какого-то взаимодействия по ним.

Не знаю, что для этого в MVP. @olgapavlova

**Comment by olgapavlova** [comment]
Ждём мнения бета-тестеров.

**Comment by olgapavlova** [comment]
Базовая функциональность сделана.
